members page done
Newton-School-Coding-Club-ABESEC/team pull request #5
Opened 2022-09-07 10:26 UTC by Ash-0803

Members page with html and css is done!

2022-09-07 14:23 UTC, pulkit-30 commented
Great work @Ash-0803 🎉 
but we need to improve UI... WDYT @IshaanTyagi?

2022-09-07 22:07 UTC, Ash-0803 commented
Yeah. Ui isn't any good right now, but we did that keeping in mind that I, ansh and ankur mainly will be working on the Ui that I have provided in the Ui issue shortly. Until then, we can do some refinements in this Ui as well. Actually I have asked ansh to do so too.

2022-09-08 04:36 UTC, pulkit-30 requested changes

2022-09-08 04:36 UTC, pulkit-30 commented on index.html
>      <title>Document</title>
Add title as `NSCC Team`

2022-09-08 04:36 UTC, pulkit-30 commented on styles.css
> +    font-family: "Poppins", sans-serif;
Add font as a root variable and use the root variable instead reset-CSS font-family globally

2022-09-08 04:36 UTC, pulkit-30 commented on styles.css
> +    box-sizing: border-box;
Add `margin` `padding` `box-sizing` in reset-css instead of font-family

2022-09-08 04:36 UTC, pulkit-30 commented on styles.css
> +    background-color: #090d16 ;
Again, declare colors in root variable and then use them

2022-09-08 04:36 UTC, pulkit-30 commented on styles.css
> +    background: linear-gradient(to right, rgba(15, 32, 39,0.8), rgba(32, 58, 67,0.5), rgba(44, 83, 100,0.2));
also, use this as root-variable

2022-09-08 04:36 UTC, pulkit-30 commented
ref https://www.w3schools.com/css/css3_variables.asp for declaring root-variables in css

2022-09-08 11:10 UTC, pulkit-30 commented on styles.css
> +    box-sizing: border-box;
now we can remove these properties from the body

2022-09-11 08:15 UTC, pulkit-30 approved these changes

2022-09-11 08:16 UTC, merged